### find all
POST http://localhost:3000/api/v1/users/all
Content-Type: application/json

### find by id
POST http://localhost:3000/api/v1/users/find
Content-Type: application/json

{
	"filters": {
		"links.accessLink": "benjamin-garrido"
	}
}

### create
POST http://localhost:3000/api/v1/guests/create
Content-Type: application/json

{
    "profile": {
        "name": "Pablo",
        "secondName": "",
        "lastName": "Luna",
        "secondLastName": ""
    },
    "menu": "regular",
    "table": "17",
    "userId": "64927a1a12c256bb43fddfea"
}
