### find all
POST http://localhost:3000/api/v1/users/all
Content-Type: application/json

### find by id
POST http://localhost:3000/api/v1/users/find
Content-Type: application/json

{
	"filters": {
		"links.accessLink": "benjamin-garrido"
	}
}

### create
POST http://localhost:3000/api/v1/guests/create
Content-Type: application/json

{
    "profile": {
        "name": "Benja",
        "secondName": "",
        "lastName": "jajaja",
        "secondLastName": ""
    },
    "menu": "regular",
    "table": "42",
    "userId": "6494884e620d5c2355f41342"
}

### update
POST http://localhost:3000/api/v1/guests/update
Content-Type: application/json

{
  "selector": {
    "_id": "6493bfd1d24c4fc6f89573e6"
  },
  "modifier": {
    "$set": {
      "profile": {
        "name": "Ben",
        "secondName": "",
        "lastName": "Garr",
        "secondLastName": ""
      }
    }
  },
  "singleton": true,
  "upsert": false
}
