### find all
POST http://localhost:3000/api/v1/users/all
Content-Type: application/json

### find by id
POST http://localhost:3000/api/v1/guests/find
Content-Type: application/json

{
	"filters": {
		"userId": "6492799012c256bb43fddfd4"
	}
}

### create
POST http://localhost:3000/api/v1/guests/create
Content-Type: application/json

{
    "profile": {
        "name": "Olga",
        "secondName": "",
        "lastName": "Solares",
        "secondLastName": ""
    },
    "menu": "regular",
    "table": "6",
    "userId": "6492799b12c256bb43fddfd6"
}

### update
POST http://localhost:3000/api/v1/guests/update
Content-Type: application/json

{
  "selector": {
    "_id": "6493bfd1d24c4fc6f89573e6"
  },
  "modifier": {
    "$set": {
      "profile": {
        "name": "Ben",
        "secondName": "",
        "lastName": "Garr",
        "secondLastName": ""
      }
    }
  },
  "singleton": true,
  "upsert": false
}
