import Head from 'next/head'
import React from "react";
import FlexRow from "@components/layouts/FlexRow";
import CalculatedSizeImage from "@components/layouts/CalculatedSizeImage";
import FlexColumn from "@components/layouts/FlexColumn";
import {Typography} from "@mui/material";


export default function Home() {




	return (
		<>
			<Head>
				<title>Arquitectura</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name='viewport'
				      content='width=device-width, height=device-height, viewport-fit=cover, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no'/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main>

				<FlexRow
					center
					sx={{
						 width: '100vw',
						background: 'black',
						padding: {
							xs: '8px',
							sm: '16px',
							md: '16px 5%',
							lg: '16px 15%',
							xl: '16px 25%',
						}
					}}>
					<FlexColumn className={'container'} sx={{ width: '50%', height:'90%', alignItems:'center', borderRadius:'4px', overflow:'hidden' }} >
						<FlexColumn className={'content'} sx={{height: '100cqw', width: '100cqw', borderRadius:'4px', background:'rgba(255,255,255,0.2)'}}>
							<CalculatedSizeImage item={{src: "https://pragmatic-package-frkme.ampt.app/public/06fa89b0-a170-4ebb-8b4d-a9986740f4df/Vertical-art.jpeg"}}/>
						</FlexColumn>
						<FlexColumn fullWidth padding={4} >
							<Typography variant='h5'>Nombre</Typography>
							<Typography variant='body1'>Author</Typography>
							<Typography variant='caption'>Caption</Typography>
						</FlexColumn>
					</FlexColumn>
					<FlexColumn className={'container'} sx={{ width: '50%', height:'90%', alignItems:'center', borderRadius:'4px', overflow:'hidden' }} >
						<FlexColumn className={'content'} sx={{height: '100cqw', width: '100cqw', borderRadius:'4px', background:'rgba(255,255,255,0.2)'}}>
							<CalculatedSizeImage item={{src: "https://pragmatic-package-frkme.ampt.app/public/ddcf310c-a7aa-4aac-a818-e74436a665e6/wind.jpg"}}/>
						</FlexColumn>
						<FlexColumn fullWidth padding={4} >
							<Typography variant='h5'>Nombre</Typography>
							<Typography variant='body1'>Author</Typography>
							<Typography variant='caption'>Caption</Typography>
						</FlexColumn>
					</FlexColumn>
				</FlexRow>


				{/*<FlexColumn gap={2} fullWidth sx={{height:'100vh'}} >*/}
				{/*	<FlexRow sx={{color:'#000' }} >*/}
				{/*		<Typography variant='body1' color={'#000'} >Category</Typography>*/}
				{/*		<Typography variant='body1' color={'#000'} >more</Typography>*/}
				{/*	</FlexRow>*/}
				{/*	<FlexRow sx={{ width:'100%', height:'clamp(600px,35vw,800px)', background:'black', padding:'8px'  }} center >*/}
				{/*		<FlexColumn sx={{ height:'100%', width:'50%' }} center >*/}
				{/*			<FlexColumn sx={{ height:'70%', width:'100%', border:'1px solid white'   }} >*/}
				{/*				<CalculatedSizeImage item={{src: ""}}/>*/}
				{/*			</FlexColumn>*/}
				{/*			<Typography variant='body1'>Nombre</Typography>*/}
				{/*			<Typography variant='body1'>Nombre</Typography>*/}
				{/*			<Typography variant='body1'>Nombre</Typography>*/}
				{/*		</FlexColumn>*/}

				{/*	</FlexRow>*/}
				{/*</FlexColumn>*/}
			</main>
		</>
	)
}



